-- Jalankan seluruh skrip ini di Supabase SQL Editor.
-- Bot memakai SUPABASE_KEY server-side. RLS tetap diaktifkan sebagai lapisan pengaman.

create table if not exists public.tid_records (
    tid varchar(30) primary key,
    description text not null,
    created_by bigint not null,
    updated_by bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint tid_digits_only check (tid ~ '^[0-9]{1,30}$'),
    constraint description_not_blank check (length(btrim(description)) > 0)
);

create table if not exists public.tid_photos (
    id bigint generated by default as identity primary key,
    tid varchar(30) not null references public.tid_records(tid) on delete cascade,
    file_id text not null,
    photo_order integer not null default 1,
    uploaded_by bigint not null,
    created_at timestamptz not null default now(),
    constraint photo_order_positive check (photo_order > 0),
    constraint file_id_not_blank check (length(btrim(file_id)) > 0)
);

create index if not exists idx_tid_photos_tid_order
    on public.tid_photos (tid, photo_order, id);

-- Satu baris settings global untuk kontrol admin. Nilai ini tetap ada setelah bot restart.
create table if not exists public.bot_settings (
    id integer primary key default 1,
    maintenance_mode boolean not null default false,
    registration_enabled boolean not null default true,
    edit_enabled boolean not null default true,
    updated_at timestamptz not null default now(),
    constraint one_settings_row check (id = 1)
);

insert into public.bot_settings (id, maintenance_mode, registration_enabled, edit_enabled)
values (1, false, true, true)
on conflict (id) do nothing;

-- Menjamin urutan foto tidak duplikat dalam satu TID.
create unique index if not exists uq_tid_photos_tid_order
    on public.tid_photos (tid, photo_order);

-- RLS aktif. Karena bot memakai service_role key di server, operasi bot tetap berjalan.
-- Jangan pernah menaruh SUPABASE_SERVICE_ROLE_KEY di aplikasi client atau membagikannya.
alter table public.tid_records enable row level security;
alter table public.tid_photos enable row level security;
alter table public.bot_settings enable row level security;

-- Opsional: trigger untuk menjaga updated_at jika data diubah dari tempat lain.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_tid_records_updated_at on public.tid_records;
create trigger trg_tid_records_updated_at
before update on public.tid_records
for each row execute function public.set_updated_at();

drop trigger if exists trg_bot_settings_updated_at on public.bot_settings;
create trigger trg_bot_settings_updated_at
before update on public.bot_settings
for each row execute function public.set_updated_at();

-- Tidak perlu menambahkan policy anon jika bot menggunakan service_role key.
-- Jika nanti dashboard/client langsung mengakses tabel, buat policy yang spesifik
-- dan jangan membuka akses tulis publik tanpa autentikasi.
